name: BlazinFly
main: iiFlamiinBlaze\BlazinFly\BlazinFly
description: An advanced survival fly plugin!
version: 1.8.7
api: 4.0.0
authors: [iiFlamiinBlaze, ZhorifCraft451]
commands:
  fly:
    description: "Command which allows flight when in Survival Mode!"
    permission: blazinfly.command
permissions:
  blazinfly.command:
    description: "BlazinFly command permission"
    default: op
  blazinfly.other:
    description: "Allow you to activate fly for other players"
    default: op